name: Echo

on:
  workflow_dispatch:

jobs:
  echo:
    strategy:
      matrix:
        os: [ubuntu-latest, self-hosted]
    runs-on: ${{ matrix.os }}
    steps:
      - name: echo github
        run: echo "${{ toJson(github) }}"

      - name: echo env
        run: echo "${{ toJson(env) }}"

      - name: echo vars
        run: echo "${{ toJson(vars) }}"
